from src.core.prompts.legal_prompts import (
    LEGAL_MAP_PROMPT,
    LEGAL_REDUCE_PROMPT,
    LEGAL_QUICK_REVIEW_PROMPT,
    LEGAL_TRAP_EXTRACTION_PROMPT,
    LEGAL_ID_CHECK_PROMPT,
    LEGAL_SYSTEM_PROMPT,
)

__all__ = [
    "LEGAL_MAP_PROMPT",
    "LEGAL_REDUCE_PROMPT",
    "LEGAL_QUICK_REVIEW_PROMPT",
    "LEGAL_TRAP_EXTRACTION_PROMPT",
    "LEGAL_ID_CHECK_PROMPT",
    "LEGAL_SYSTEM_PROMPT",
]
